apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-8c74"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-8c74"
  template:
    metadata:
      labels:
        app: "myakscluster-8c74"
    spec:
      containers:
        - name: "myakscluster-8c74"
          image: "azureakscontainer.azurecr.io/myakscluster"
          ports:
          - containerPort: 80